language: go

dist: bionic

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

git:
  depth: 1

matrix:
  allow_failures:
    - go: tip

os:
  - osx
  - linux

before_install:
  # Call xvfb directly on linux runs and give it time to start
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    export DISPLAY=:99.0;
    Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    sleep 3;
    sudo apt-get update && sudo apt-get install -y libsecret-1-0;
    fi

install:
  - TRAVIS_NODE_VERSION="8";
  # Clear out whatever version of NVM Travis has as it is old.
  - rm -rf ~/.nvm;
    # Grab NVM.
  - git clone https://github.com/creationix/nvm.git ~/.nvm;
    # Checkout the latest stable tag.
    # Note that you can just hardcode a preferred version here.
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`);
    # Install the desired version of Node
  - source ~/.nvm/nvm.sh;
  - nvm install $TRAVIS_NODE_VERSION;
  - npm install
  - npm run vscode:prepublish
  - go get -u -v github.com/acroca/go-symbols
  - go get -u -v github.com/cweill/gotests/...
  - go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct
  - go get -u -v github.com/haya14busa/goplay/cmd/goplay
  - go get -u -v github.com/mdempsky/gocode
  - go get -u -v github.com/ramya-rao-a/go-outline
  - go get -u -v github.com/rogpeppe/godef
  - go get -u -v github.com/sqs/goreturns
  - go get -u -v github.com/uudashr/gopkgs/v2/cmd/gopkgs
  - go get -u -v github.com/zmb3/gogetdoc
  - go get -u -v golang.org/x/lint/golint
  - go get -u -v golang.org/x/tools/cmd/gorename
  - GO111MODULE=on go get golang.org/x/tools/gopls

script:
  - npm run lint
  - npm run unit-test
  - npm test --silent
